//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace N4_ClubSocial.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("N4_ClubSocial.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advertencia.
        /// </summary>
        internal static string Advertencia {
            get {
                return ResourceManager.GetString("Advertencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A&amp;filiar.
        /// </summary>
        internal static string Afiliar {
            get {
                return ResourceManager.GetString("Afiliar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afiliar.
        /// </summary>
        internal static string AfiliarPestaña {
            get {
                return ResourceManager.GetString("AfiliarPestaña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Agregar Autorizado.
        /// </summary>
        internal static string AgregarAutorizado {
            get {
                return ResourceManager.GetString("AgregarAutorizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autorizados.
        /// </summary>
        internal static string Autorizados {
            get {
                return ResourceManager.GetString("Autorizados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Buscar.
        /// </summary>
        internal static string Buscar {
            get {
                return ResourceManager.GetString("Buscar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Busqueda de Socio.
        /// </summary>
        internal static string BusquedaDeSocio {
            get {
                return ResourceManager.GetString("BusquedaDeSocio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cédula.
        /// </summary>
        internal static string Cedula {
            get {
                return ResourceManager.GetString("Cedula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cédula Socio.
        /// </summary>
        internal static string CedulaSocio {
            get {
                return ResourceManager.GetString("CedulaSocio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliente.
        /// </summary>
        internal static string Cliente {
            get {
                return ResourceManager.GetString("Cliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concepto.
        /// </summary>
        internal static string Concepto {
            get {
                return ResourceManager.GetString("Concepto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consumos.
        /// </summary>
        internal static string Consumos {
            get {
                return ResourceManager.GetString("Consumos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contabilidad.
        /// </summary>
        internal static string Contabilidad {
            get {
                return ResourceManager.GetString("Contabilidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datos Personales.
        /// </summary>
        internal static string DatosPersonales {
            get {
                return ResourceManager.GetString("DatosPersonales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primero debe buscar socio..
        /// </summary>
        internal static string DebeBuscarSocio {
            get {
                return ResourceManager.GetString("DebeBuscarSocio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El valor de la cédula debe ser numérico..
        /// </summary>
        internal static string DebeCedulaSerNumerico {
            get {
                return ResourceManager.GetString("DebeCedulaSerNumerico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe ingresar un número de cédula..
        /// </summary>
        internal static string DebeIngresarCedula {
            get {
                return ResourceManager.GetString("DebeIngresarCedula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe ingresar el concepto de la factura..
        /// </summary>
        internal static string DebeIngresarConcepto {
            get {
                return ResourceManager.GetString("DebeIngresarConcepto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe ingresar el nombre del socio..
        /// </summary>
        internal static string DebeIngresarNombre {
            get {
                return ResourceManager.GetString("DebeIngresarNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El valor del concepto debe ser numérico..
        /// </summary>
        internal static string DebeValorSerNumerico {
            get {
                return ResourceManager.GetString("DebeValorSerNumerico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facturas.
        /// </summary>
        internal static string Facturas {
            get {
                return ResourceManager.GetString("Facturas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No hay facturas por pagar..
        /// </summary>
        internal static string NoHayFacturasPorPagar {
            get {
                return ResourceManager.GetString("NoHayFacturasPorPagar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        internal static string Nombre {
            get {
                return ResourceManager.GetString("Nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrtizOL - Club - [Cupi2.NET].
        /// </summary>
        internal static string NombreAplicacion {
            get {
                return ResourceManager.GetString("NombreAplicacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Club.
        /// </summary>
        internal static string NombreApp {
            get {
                return ResourceManager.GetString("NombreApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Op&amp;ción 1.
        /// </summary>
        internal static string Opcion1 {
            get {
                return ResourceManager.GetString("Opcion1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opció&amp;n 2.
        /// </summary>
        internal static string Opcion2 {
            get {
                return ResourceManager.GetString("Opcion2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P&amp;agar Factura.
        /// </summary>
        internal static string PagarFactura {
            get {
                return ResourceManager.GetString("PagarFactura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Registrar.
        /// </summary>
        internal static string Registrar {
            get {
                return ResourceManager.GetString("Registrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro de Consumos.
        /// </summary>
        internal static string RegistroConsumos {
            get {
                return ResourceManager.GetString("RegistroConsumos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mensaje.
        /// </summary>
        internal static string Satisfactorio {
            get {
                return ResourceManager.GetString("Satisfactorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario ha sido ingresado..
        /// </summary>
        internal static string UsuarioRegistrado {
            get {
                return ResourceManager.GetString("UsuarioRegistrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor.
        /// </summary>
        internal static string Valor {
            get {
                return ResourceManager.GetString("Valor", resourceCulture);
            }
        }
    }
}
